Config = {}

Config.Locations = {
    ["main"] = {
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },
    ["thermite"] = {
        x = 379.66,
        y = -908.27,
        z = 29.42,
        isDone = false,
        isBusy = false,
    },
    ["takeables"] = {
        [1] = {
            x = 346.25,
            y = -917.14,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "ps5", amount = 1},
        },
        [2] = {
            x = 346.16,
            y = -918.89,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "xboxx", amount = 1},
        },
        [3] = {
            x = 346.0,
            y = -910.76,
            z =  29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "ps2", amount = 1},
        },
        [4] = {
            x = 346.17,
            y = -908.3,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "gamecube", amount = 1},
        },
        [5] = {
            x = 338.9,
            y = -933.79,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "awp", amount = 1},
        },
        [6] = {
            x = 342.53,
            y = -933.51,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "awp", amount = 1},
        },
        [7] = {
            x = 342.65,
            y = -936.85,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "awp", amount = 1},
        },
        [8] = {
            x = 339.34,
            y = -937.03,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "awp", amount = 1},
        },
        [9] = {
            x = 324.2,
            y = -923.12,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "actionfigure", amount = 10},
        },
        [10] = {
            x = 346.16,
            y = -927.37,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "ps5", amount = 1},
        },
        [11] = {
            x = 349.29,
            y = -903.96,
            z = 29.25,
            isDone = false,
            isBusy = false,
            reward =  {name = "gamecube", amount = 1},
        },
    },
    ["safe"] = {
        x = 323.84,
        y = -928.3,
        z = 29.25,
        isDone = false,
        isBusy = false,
    }
}

Config.MaleNoHandshoes = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [18] = true,
    [26] = true,
    [52] = true,
    [53] = true,
    [54] = true,
    [55] = true,
    [56] = true,
    [57] = true,
    [58] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [112] = true,
    [113] = true,
    [114] = true,
    [118] = true,
    [125] = true,
    [132] = true,
}

Config.FemaleNoHandshoes = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [19] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [63] = true,
    [64] = true,
    [65] = true,
    [66] = true,
    [67] = true,
    [68] = true,
    [69] = true,
    [70] = true,
    [71] = true,
    [129] = true,
    [130] = true,
    [131] = true,
    [135] = true,
    [142] = true,
    [149] = true,
    [153] = true,
    [157] = true,
    [161] = true,
    [165] = true,
}
